namespace UAG.enums
{
public enum GameStates
{
    PLUG_ON, SKY_BRIDGE_ON, ITEM_TEDDY, ITEM_LIFESAVER, BELLS, 
    ITEM_KEYCARD, MAINFRAME_OPEN, HOTEL_213_OPEN, MEADOW, FERRIS_STOPPED,
    ADDICT_LEMON, ADDICT_DRUGS, ITEM_DRUGS, ITEM_LEMOMN, ITEM_LEMONADE, SPOILED_LEMON,
    ITEM_WRATH, ITEM_NONE, TREE_DEAD, NO_LEMON
}
}